import './globals.scss';

import { ChakraProvider } from '@chakra-ui/react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import BottomTabNavigator from '@/share/bottomTabNavigation/bottomTabNavigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ChakraProvider>
          <main className='page-body'>{children}</main>
          <footer>
            <BottomTabNavigator route='home' />
          </footer>
        </ChakraProvider>
      </body>
    </html>
  );
}
